#!/usr/bin/env python3
from pathlib import Path

from coordinates import get_coordinates
from exceptions import CantGetCoordinates, ApiServiceError
from history import save_weather, JsonFileWeatherStorage, PlainFileWeatherStorage
from weather_api_service import get_weather
from weather_formatter import format_weather


def main():
    try:
        coordinates = get_coordinates()
    except CantGetCoordinates:
        print("Couldn't get GPS coordinates")
        exit(1)
    try:
        weather = get_weather(coordinates)
        print(format_weather(weather))

        save_weather(
            weather,
            PlainFileWeatherStorage(Path.cwd() / "history.txt")  # Or JsonFileWeatherStorage
        )

    except ApiServiceError:
        print(f"Couldn't get weather by GPS coordinates {coordinates}")
        exit(1)


if __name__ == "__main__":
    main()
